from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow
import sys


class Ui_MainWindow(object):

    def setup(self, main_window):
        super().__init__()

        main_window.setObjectName("MainWindow")
        main_window.resize(500, 700)
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("central widget")

        self.result_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(0, 0, 500, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("background-color: rgb(203, 203, 203);\n"
                                        "color: rgb(0, 0, 0);")
        self.result_label.setObjectName("result_label")

        self.button_0 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_0.setGeometry(QtCore.QRect(125, 575, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_0.setFont(font)
        self.button_0.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_0.setObjectName("button_0")

        self.button_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(0, 450, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_1.setFont(font)
        self.button_1.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_1.setObjectName("button_1")

        self.button_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(125, 450, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_2.setFont(font)
        self.button_2.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_2.setObjectName("button_2")

        self.button_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(250, 450, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_3.setFont(font)
        self.button_3.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_3.setObjectName("button_3")

        self.button_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(0, 325, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_4.setFont(font)
        self.button_4.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_4.setObjectName("button_4")

        self.button_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(125, 325, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_5.setFont(font)
        self.button_5.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_5.setObjectName("button_5")

        self.button_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_6.setGeometry(QtCore.QRect(250, 325, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_6.setFont(font)
        self.button_6.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_6.setObjectName("button_6")

        self.button_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_9.setGeometry(QtCore.QRect(250, 200, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_9.setFont(font)
        self.button_9.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_9.setObjectName("button_9")

        self.button_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_8.setGeometry(QtCore.QRect(125, 200, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_8.setFont(font)
        self.button_8.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_8.setObjectName("button_8")

        self.button_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_7.setGeometry(QtCore.QRect(0, 200, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.button_7.setFont(font)
        self.button_7.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.button_7.setObjectName("button_7")

        self.equal_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.equal_button.setGeometry(QtCore.QRect(375, 575, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.equal_button.setFont(font)
        self.equal_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.equal_button.setObjectName("equal_button")

        self.plus_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.plus_button.setGeometry(QtCore.QRect(375, 450, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.plus_button.setFont(font)
        self.plus_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.plus_button.setObjectName("plus_button")

        self.multiply_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.multiply_button.setGeometry(QtCore.QRect(375, 200, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.multiply_button.setFont(font)
        self.multiply_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.multiply_button.setObjectName("multiply_button")

        self.minus_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minus_button.setGeometry(QtCore.QRect(375, 325, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.minus_button.setFont(font)
        self.minus_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.minus_button.setObjectName("minus_button")

        self.percent_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.percent_button.setGeometry(QtCore.QRect(250, 80, 125, 120))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.percent_button.setFont(font)
        self.percent_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.percent_button.setObjectName("percent_button")

        self.clear_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(0, 80, 125, 120))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.clear_button.setObjectName("clear_button")

        self.bracket_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bracket_button.setGeometry(QtCore.QRect(125, 80, 125, 120))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.bracket_button.setFont(font)
        self.bracket_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.bracket_button.setObjectName("bracket_button")

        self.division_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.division_button.setGeometry(QtCore.QRect(375, 80, 125, 120))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.division_button.setFont(font)
        self.division_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.division_button.setObjectName("division_button")

        self.negation_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.negation_button.setGeometry(QtCore.QRect(0, 575, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.negation_button.setFont(font)
        self.negation_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.negation_button.setObjectName("negation_button")

        self.comma_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.comma_button.setGeometry(QtCore.QRect(250, 575, 125, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.comma_button.setFont(font)
        self.comma_button.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.comma_button.setObjectName("comma_button")

        main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.result_label.setText(_translate("MainWindow", "0"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.equal_button.setText(_translate("MainWindow", "="))
        self.plus_button.setText(_translate("MainWindow", "+"))
        self.multiply_button.setText(_translate("MainWindow", "*"))
        self.minus_button.setText(_translate("MainWindow", "-"))
        self.percent_button.setText(_translate("MainWindow", "%"))
        self.clear_button.setText(_translate("MainWindow", "C"))
        self.bracket_button.setText(_translate("MainWindow", "()"))
        self.division_button.setText(_translate("MainWindow", "/"))
        self.negation_button.setText(_translate("MainWindow", "+/-"))
        self.comma_button.setText(_translate("MainWindow", "."))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setup(MainWindow)
    MainWindow.show()

    app.exec()
